### ISSUE TITLE
OSError: access violation writing 0x589F7000 in c_FastDTWBD_wrapper.py

### ISSUE THREAD

**Issue by bhattarai333** [r4victor/afaligner#1] opened 2021-02-10 00:49 UTC
I'm trying to run afaligner on my own and I keep running into this issue. I've found [this stackoverflow question](https://stackoverflow.com/questions/37973033/ctypes-python3-5-oserror-exception-access-violation-writing-0x00000000), but this is way over my head now. Sorry if this isn't the place to post this, and I'd be grateful for some guidance on how I could fix this issue.

> N:462470 L:12 M:64582 Skip:0.75 R:100 t-shape: (64582, 12)
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    main()
  File "main.py", line 105, in main
    sync_map = sync.prepare(book)
  File "C:\Users\Josh\PycharmProjects\VideoBook\sync.py", line 48, in prepare
    sync(text_dir, audio_dir, output_dir)
  File "C:\Users\Josh\PycharmProjects\VideoBook\sync.py", line 37, in sync
    skip_penalty=alignment_skip_penalty
  File "C:\Users\Josh\PycharmProjects\VideoBook\afaligner\main.py", line 89, in align
    radius=radius
  File "C:\Users\Josh\PycharmProjects\VideoBook\afaligner\main.py", line 199, in build_sync_map
    _, path = c_FastDTWBD(text_mfcc_sequence, audio_mfcc_sequence, skip_penalty, radius=radius)
  File "C:\Users\Josh\PycharmProjects\VideoBook\afaligner\c_dtwbd_wrapper.py", line 30, in c_FastDTWBD
    path_buffer.ctypes
OSError: exception: access violation writing 0x589F7000

**Comment by r4victor** [comment] 2021-02-10 07:17
Hi @bhattarai333! I found a problem with the code that is probably related to your issue. I used `int64` as a type of `path_buffer` elements:

```python
def c_FastDTWBD(s, t, skip_penalty, radius):
    # ...
    path_buffer = np.empty((n+m, 2), dtype='int64')
    # ...
```

This code is not portable. It works on 64-bit platforms but should break on 32-bit platforms. I now fixed this problem by changing the type to `uintp`. Are you on 32-bit platform? Try the latest 0.1.2 version to see if the problem is fixed. Unfortunately, I'm unable to compile the extension for 32-bit platform to test it myself because I'm on Mac OS.

**Comment by bhattarai333** [comment] 2021-02-10 20:39
> N:462470 L:12 M:64582 Skip:0.75 R:100 t-shape: (64582, 12)
pdist:c_double(0.0) pbuf:[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    main()
  File "main.py", line 105, in main
    sync_map = sync.prepare(book)
  File "C:\Users\Josh\PycharmProjects\VideoBook\sync.py", line 48, in prepare
    sync(text_dir, audio_dir, output_dir)
  File "C:\Users\Josh\PycharmProjects\VideoBook\sync.py", line 37, in sync
    skip_penalty=alignment_skip_penalty
  File "C:\Users\Josh\PycharmProjects\VideoBook\afaligner\main.py", line 89, in align
    radius=radius
  File "C:\Users\Josh\PycharmProjects\VideoBook\afaligner\main.py", line 199, in build_sync_map
    _, path = c_FastDTWBD(text_mfcc_sequence, audio_mfcc_sequence, skip_penalty, radius=radius)
  File "C:\Users\Josh\PycharmProjects\VideoBook\afaligner\c_dtwbd_wrapper.py", line 31, in c_FastDTWBD
    path_buffer.ctypes
OSError: exception: access violation writing 0x00000000

Unfortunately, I'm getting the same error, but with 0x00000000 every time now after replacing 'int64' with 'uintp'. Weird part is, I'm pretty sure my machine is 64 bit anyway, so I'm not sure why I've been running into this issue in the first place.

**Comment by r4victor** [comment] 2021-02-11 10:08
I think I figured this out. You're using Windows, and I haven't tried to install `afaligner` on Windows before. I should better warn about this. Anyway, today I tried to get it worked on Windows and came into a couple of issues that don't show up on Mac OS / Linux. I'm surprised you were able to compile the `afaligner`'s C extension at all. Did you have to modify the code? Leaving aside compiling issues, the real problem was that the `radius` and `skip_penalty` arguments were passed to `FastDTWBD()`  in the wrong order, like this:

```python
def c_FastDTWBD(s, t, skip_penalty, radius):
    # ...
    path_len = c_module.FastDTWBD(
        # ...
        radius,
        ctypes.c_double(skip_penalty),
        # ...
    )
    # ...
```
But they should be passed like this:

```python
def c_FastDTWBD(s, t, skip_penalty, radius):
    # ...
    path_len = c_module.FastDTWBD(
        # ...
        ctypes.c_double(skip_penalty),
        radius,
        # ...
    )
    # ...
```

The question is, of course: How did it work at all? So I took a look at how `ctypes` passes arguments to a C function.  It turned out that the order of arguments that have unique type doesn't matter. `ctypes` tries to be clever about it and puts arguments according to their types. On Windows the logic is somewhat different and the order matters as you would expect. This behavior seems to be undocumented.

I successfully installed and run `afaligner` on Windows and I hope you'll be able too. Try to run tests on the latest version.

**Comment by bhattarai333** [comment] 2021-02-11 17:04
Strange, I'm able to pass every test case:

> =========================================================================================================================== test session starts ===========================================================================================================================
platform win32 -- Python 3.7.4, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: C:\Users\Josh\PycharmProjects\VideoBook\afaligner
collected 4 items                                                                                                                                                                                                                                                          
test_dtwbd.py ....                                                                                                                                                                                                                                                   [100%]
============================================================================================================================ 4 passed in 0.53s ============================================================================================================================

But when run it, I still get the same error:

> N:15937 L:12 M:20614 Skip:0.75 R:100 t-shape: (20614, 12)
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    main()
  File "main.py", line 105, in main
    sync_map = sync.prepare(book)
  File "C:\Users\Josh\PycharmProjects\VideoBook\sync.py", line 40, in prepare
    sync(text_dir, audio_dir, output_dir)
  File "C:\Users\Josh\PycharmProjects\VideoBook\sync.py", line 29, in sync
    skip_penalty=alignment_skip_penalty
  File "C:\Users\Josh\PycharmProjects\VideoBook\afaligner\main.py", line 89, in align
    radius=radius
  File "C:\Users\Josh\PycharmProjects\VideoBook\afaligner\main.py", line 199, in build_sync_map
    _, path = c_FastDTWBD(text_mfcc_sequence, audio_mfcc_sequence, skip_penalty, radius=radius)
  File "C:\Users\Josh\PycharmProjects\VideoBook\afaligner\c_dtwbd_wrapper.py", line 31, in c_FastDTWBD
    path_buffer.ctypes.data_as(ctypes.POINTER(ctypes.c_size_t))
OSError: exception: access violation writing 0x00000000

I did not make any changes to dtwbd.c, and I compiled it using the Windows MinGW compiler. 

Do my values for n, l, m and t look correct? If you're able to run it on Windows there might be something wrong with my inputs.

**Comment by r4victor** [comment] 2021-02-12 05:11
Your input values look okay. Could you tell me what they are exactly so I can reproduce the problem?

**Comment by bhattarai333** [comment] 2021-02-12 05:27
Do you mean the files I'm trying to align with?

The exact values are above:
N:15937 L:12 M:20614 Skip:0.75 R:100 t-shape: (20614, 12)

**Comment by r4victor** [comment] 2021-02-12 07:34
Yes, any input files that lead to this error.

**Comment by bhattarai333** [comment] 2021-02-12 07:51
I've made a temporary repo with the audio and generated xhtml files: 
https://github.com/bhattarai333/ExampleAligner

And here's the output I'm getting with these files:

> N:13562 L:12 M:18332 Skip:0.75 R:100 t-shape: (18332, 12)
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    main()
  File "main.py", line 105, in main
    sync_map = sync.prepare(book)
  File "C:\Users\Josh\PycharmProjects\VideoBook\sync.py", line 40, in prepare
    sync(text_dir, audio_dir, output_dir)
  File "C:\Users\Josh\PycharmProjects\VideoBook\sync.py", line 29, in sync
    skip_penalty=alignment_skip_penalty
  File "C:\Users\Josh\PycharmProjects\VideoBook\afaligner\main.py", line 89, in align
    radius=radius
  File "C:\Users\Josh\PycharmProjects\VideoBook\afaligner\main.py", line 199, in build_sync_map
    _, path = c_FastDTWBD(text_mfcc_sequence, audio_mfcc_sequence, skip_penalty, radius=radius)
  File "C:\Users\Josh\PycharmProjects\VideoBook\afaligner\c_dtwbd_wrapper.py", line 31, in c_FastDTWBD
    path_buffer.ctypes.data_as(ctypes.POINTER(ctypes.c_size_t))
OSError: exception: access violation writing 0x00000000

@r4victor thanks so much for working with me so far!

**Comment by r4victor** [comment] 2021-02-12 13:05
I have some good and some bad news for your. First of all, I had no trouble running **afaligner** on your data on Mac OS. On Windows, however, I got OSError indeed.

The good news is that I found the reason for that: `malloc()` failed and returned a `NULL` pointer which the code didn't check. This is, of course, buggy code, but it worked on Mac OS/Linux because they overcommit – give out more virtual memory than physical memory exists. The current code relies on overcommit. And I didn't know that Windows do not that (I didn't think about it really). Now I added the check and a test, so when `malloc()` fails, the appropriate error is raised.

The bad news is that to change the allocation strategy, the algorithm must be changed too and I don't have the time at the moment to do that. I opened a [new issue](https://github.com/r4victor/afaligner/issues/2) that I'm going to address later. Until then the README will be saying that Windows is not supported.

I'm sorry that you had such a frustrating experience. I should warn about supported platforms in README. Thank you for your patience. This issue helped to fix a couple of bugs.

At the moment I can only suggest you to use **afaligner** on Linux / Mac OS if you can. This should work.

**Comment by bhattarai333** [comment] 2021-02-12 22:06
Thank you for all your investigating, no need to apologize, I'm just glad we found the cause of the issue. I'll just wait for when/if windows is supported or use a different aligner, thanks again for working with me on this.

**Comment by r4victor** [comment] 2021-02-13 04:12
Alright. I'm closing the issue.

**Closed as completed by r4victor** 2021-02-13 04:12 UTC

**Comment by bhattarai333** [comment] 2021-02-24 06:11
Sorry to take up more of your time with this @r4victor, but I've spent some time learning how to setup a Ubuntu VM and I'm still running into a segmentation fault in the same spot. 

Does a VM make no difference for this overcommit issue? Do I need an actual machine running linux/mac OS to avoid the issue?

The only output I get this time around is this:

> N:36227 L:12 M:50497 Skip:0.75 R:100 t-shape: {50497, 12)
Segementation fault (core dumped)

**Comment by r4victor** [comment] 2021-02-24 12:32
Yes, you need an actual machine running linux/mac OS. The VM doesn't help because ultimately it's the Windows API function that allocates memory.

**Comment by bhattarai333** [comment] 2021-03-03 04:33
Hello again, I've got my hands on a Linux machine, but I'm still getting a segmentation fault in the same spot. Things are a bit different this time though.

When I run the tests it at least gives me an error like it should:

> ============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/josh/Desktop
collected 5 items                                                              
tests/test_dtwbd.py ....Fatal Python error: Segmentation fault
Current thread 0x00007fa31ce8b740 (most recent call first):
  File "/home/josh/.local/lib/python3.8/site-packages/afaligner/c_dtwbd_wrapper.py", line 36 in c_FastDTWBD

And I at least get a more coherent error message when the program fails:

> ERROR: malloc() failed when allocating D_matrix
Traceback (most recent call last):
  File "main.py", line 124, in <module>
    main()
  File "main.py", line 110, in main
    sync_map = sync.prepare(book)
  File "/home/josh/Desktop/VideoBook/sync.py", line 132, in prepare
    afa_prepare(book)
  File "/home/josh/Desktop/VideoBook/sync.py", line 37, in afa_prepare
    afaligner_sync(text_dir, audio_dir, output_dir)
  File "/home/josh/Desktop/VideoBook/sync.py", line 19, in afaligner_sync
    sync_map = align(
  File "/home/josh/.local/lib/python3.8/site-packages/afaligner/__init__.py", line 87, in align
    sync_map = build_sync_map(
  File "/home/josh/.local/lib/python3.8/site-packages/afaligner/__init__.py", line 202, in build_sync_map
    _, path = c_FastDTWBD(text_mfcc_sequence, audio_mfcc_sequence, skip_penalty, radius=radius)
  File "/home/josh/.local/lib/python3.8/site-packages/afaligner/c_dtwbd_wrapper.py", line 49, in c_FastDTWBD
    raise FastDTWBDError(
afaligner.c_dtwbd_wrapper.FastDTWBDError: The FastDTWDB() C function raised an error. See stderr for more details.

Malloc is still failing, so my only guesses are that I haven't compiled the c code correctly or overcommit is somehow not enabled on my version of Ubuntu, do you have any ideas?

Ubuntu version:
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

**Comment by r4victor** [comment] 2021-03-03 12:38
I think it's because of overcommit. Try to set `vm.overcommit_memory` to `1`, like so:

```
$ echo 1 | sudo tee /proc/sys/vm/overcommit_memory

**Comment by bhattarai333** [comment] 2021-03-03 22:16
That did the trick! Thanks so much for all of your help, glad to say it's working for me now.

**Comment by smiclea** [comment] 2021-04-30 15:57
FYI using

> $ echo 1 | sudo tee /proc/sys/vm/overcommit_memory

is also a fix for Ubuntu on a VM on Windows.

Thank you so much for this library.

**Comment by r4victor** [comment] 2021-05-01 09:14
Thanks for the information, @smiclea! I'm surprised to learn this. Need to look at how VMs work.
